import type { Job } from "@job-tracker/types";
import { JobStatus, JobPriority } from "@job-tracker/types";

export const seedJobs: Job[] = [
  {
    id: "seed-job-1",
    companyName: "Google",
    location: "Mountain View, CA",
    status: JobStatus.Interviewing,
    roleOrPosition: "Software Engineer II",
    mainContact: "Jane Smith",
    contactEmail: "jane.smith@google.com",
    dateApplied: "2024-03-01",
    lastContact: "2024-03-15",
    likelihoodOfHiring: 70,
    tags: ["FAANG", "SWE", "Big Tech"],
    notes: "Two technical rounds completed. System design next.",
    salaryRange: "$180k – $220k",
    jobPostingUrl: "https://careers.google.com",
    priority: JobPriority.High,
    requiresFollowUp: false,
    createdAt: "2024-03-01T10:00:00.000Z",
    updatedAt: "2024-03-15T14:00:00.000Z",
  },
  {
    id: "seed-job-2",
    companyName: "Stripe",
    location: "San Francisco, CA (Remote)",
    status: JobStatus.Applied,
    roleOrPosition: "Full Stack Engineer",
    dateApplied: "2024-03-05",
    likelihoodOfHiring: 50,
    tags: ["Fintech", "Remote"],
    notes: "Applied via referral from LinkedIn connection.",
    salaryRange: "$160k – $200k",
    jobPostingUrl: "https://stripe.com/jobs",
    priority: JobPriority.High,
    requiresFollowUp: true,
    createdAt: "2024-03-05T09:00:00.000Z",
    updatedAt: "2024-03-05T09:00:00.000Z",
  },
  {
    id: "seed-job-3",
    companyName: "Notion",
    location: "New York, NY",
    status: JobStatus.OACompleted,
    roleOrPosition: "Frontend Engineer",
    mainContact: "Alex Chen",
    dateApplied: "2024-03-10",
    lastContact: "2024-03-20",
    likelihoodOfHiring: 60,
    tags: ["Startup", "SaaS", "Product"],
    notes: "OA completed. Waiting on interview invite.",
    priority: JobPriority.Medium,
    requiresFollowUp: false,
    createdAt: "2024-03-10T11:00:00.000Z",
    updatedAt: "2024-03-20T16:00:00.000Z",
  },
  {
    id: "seed-job-4",
    companyName: "Meta",
    location: "Menlo Park, CA",
    status: JobStatus.Rejected,
    roleOrPosition: "Software Engineer",
    dateApplied: "2024-02-15",
    lastContact: "2024-02-28",
    likelihoodOfHiring: 0,
    tags: ["FAANG", "SWE"],
    notes: "Rejected after phone screen.",
    priority: JobPriority.High,
    requiresFollowUp: false,
    createdAt: "2024-02-15T08:00:00.000Z",
    updatedAt: "2024-02-28T10:00:00.000Z",
  },
  {
    id: "seed-job-5",
    companyName: "Linear",
    location: "Remote",
    status: JobStatus.RecruiterReachout,
    roleOrPosition: "Senior Frontend Engineer",
    mainContact: "Sam Torres",
    contactEmail: "sam@linear.app",
    dateApplied: "2024-03-22",
    likelihoodOfHiring: 65,
    tags: ["Remote", "Startup", "Product"],
    notes: "Recruiter reached out via LinkedIn. Interesting product.",
    salaryRange: "$170k – $210k",
    priority: JobPriority.Medium,
    requiresFollowUp: true,
    createdAt: "2024-03-22T12:00:00.000Z",
    updatedAt: "2024-03-22T12:00:00.000Z",
  },
  {
    id: "seed-job-6",
    companyName: "Vercel",
    location: "Remote",
    status: JobStatus.FinalRound,
    roleOrPosition: "Software Engineer – Developer Experience",
    dateApplied: "2024-02-28",
    lastContact: "2024-03-25",
    likelihoodOfHiring: 80,
    tags: ["Remote", "DevTools", "Open Source"],
    notes: "Final round virtual on-site scheduled for next week.",
    salaryRange: "$155k – $195k",
    priority: JobPriority.High,
    requiresFollowUp: false,
    createdAt: "2024-02-28T09:00:00.000Z",
    updatedAt: "2024-03-25T15:00:00.000Z",
  },
];
