import type { Problem } from "@job-tracker/types";
import {
  ProblemDifficulty,
  ProblemStatus,
  ProblemType,
} from "@job-tracker/types";

export const seedProblems: Problem[] = [
  {
    id: "seed-prob-1",
    name: "Two Sum",
    url: "https://leetcode.com/problems/two-sum/",
    type: ProblemType.Array,
    difficulty: ProblemDifficulty.Easy,
    status: ProblemStatus.Solved,
    topicTags: ["Array", "Hash Table"],
    solvedAt: "2024-02-10",
    revisionCount: 2,
    isFavorite: true,
    notes: "Classic hash map solution. O(n) time.",
    createdAt: "2024-02-10T10:00:00.000Z",
    updatedAt: "2024-02-20T10:00:00.000Z",
  },
  {
    id: "seed-prob-2",
    name: "Longest Substring Without Repeating Characters",
    url: "https://leetcode.com/problems/longest-substring-without-repeating-characters/",
    type: ProblemType.SlidingWindow,
    difficulty: ProblemDifficulty.Medium,
    status: ProblemStatus.Solved,
    topicTags: ["String", "Sliding Window", "Hash Table"],
    solvedAt: "2024-02-12",
    revisionCount: 1,
    isFavorite: false,
    notes: "Sliding window with a set.",
    createdAt: "2024-02-12T10:00:00.000Z",
    updatedAt: "2024-02-12T10:00:00.000Z",
  },
  {
    id: "seed-prob-3",
    name: "Binary Tree Level Order Traversal",
    url: "https://leetcode.com/problems/binary-tree-level-order-traversal/",
    type: ProblemType.Tree,
    difficulty: ProblemDifficulty.Medium,
    status: ProblemStatus.Solved,
    topicTags: ["Tree", "BFS", "Queue"],
    solvedAt: "2024-02-15",
    revisionCount: 0,
    isFavorite: false,
    notes: "BFS with queue, track level size.",
    createdAt: "2024-02-15T10:00:00.000Z",
    updatedAt: "2024-02-15T10:00:00.000Z",
  },
  {
    id: "seed-prob-4",
    name: "Merge K Sorted Lists",
    url: "https://leetcode.com/problems/merge-k-sorted-lists/",
    type: ProblemType.Heap,
    difficulty: ProblemDifficulty.Hard,
    status: ProblemStatus.NeedsRevision,
    topicTags: ["Linked List", "Heap", "Divide and Conquer"],
    attemptedAt: "2024-02-20",
    revisionCount: 3,
    isFavorite: true,
    notes: "Use a min-heap. Need to revisit the divide and conquer approach.",
    createdAt: "2024-02-20T10:00:00.000Z",
    updatedAt: "2024-03-01T10:00:00.000Z",
  },
  {
    id: "seed-prob-5",
    name: "Coin Change",
    url: "https://leetcode.com/problems/coin-change/",
    type: ProblemType.DynamicProgramming,
    difficulty: ProblemDifficulty.Medium,
    status: ProblemStatus.Solved,
    topicTags: ["Dynamic Programming", "BFS"],
    solvedAt: "2024-02-22",
    revisionCount: 1,
    isFavorite: false,
    notes: "Classic DP. dp[i] = min coins to make amount i.",
    createdAt: "2024-02-22T10:00:00.000Z",
    updatedAt: "2024-02-22T10:00:00.000Z",
  },
  {
    id: "seed-prob-6",
    name: "Number of Islands",
    url: "https://leetcode.com/problems/number-of-islands/",
    type: ProblemType.Graph,
    difficulty: ProblemDifficulty.Medium,
    status: ProblemStatus.Attempted,
    topicTags: ["Graph", "BFS", "DFS", "Union Find"],
    attemptedAt: "2024-03-01",
    revisionCount: 1,
    isFavorite: false,
    notes: "DFS/BFS flood fill approach. Mark visited in-place.",
    createdAt: "2024-03-01T10:00:00.000Z",
    updatedAt: "2024-03-01T10:00:00.000Z",
  },
  {
    id: "seed-prob-7",
    name: "Trapping Rain Water",
    url: "https://leetcode.com/problems/trapping-rain-water/",
    type: ProblemType.TwoPointers,
    difficulty: ProblemDifficulty.Hard,
    status: ProblemStatus.NotStarted,
    topicTags: ["Array", "Two Pointers", "Stack"],
    revisionCount: 0,
    isFavorite: false,
    createdAt: "2024-03-05T10:00:00.000Z",
    updatedAt: "2024-03-05T10:00:00.000Z",
  },
  {
    id: "seed-prob-8",
    name: "Valid Parentheses",
    url: "https://leetcode.com/problems/valid-parentheses/",
    type: ProblemType.Stack,
    difficulty: ProblemDifficulty.Easy,
    status: ProblemStatus.Solved,
    topicTags: ["String", "Stack"],
    solvedAt: "2024-02-08",
    revisionCount: 0,
    isFavorite: false,
    notes: "Classic stack problem.",
    createdAt: "2024-02-08T10:00:00.000Z",
    updatedAt: "2024-02-08T10:00:00.000Z",
  },
];
