import type { Resource } from "@job-tracker/types";
import { ResourceCategory, ResourceType } from "@job-tracker/types";

export const seedResources: Resource[] = [
  {
    id: "seed-res-1",
    title: "NeetCode 150",
    description: "Curated list of 150 LeetCode problems for interview prep.",
    url: "https://neetcode.io/practice",
    category: ResourceCategory.LeetCode,
    type: ResourceType.Website,
    tags: ["leetcode", "patterns", "must-do"],
    notes: "Best structured resource for interview prep.",
    createdAt: "2024-01-01T10:00:00.000Z",
    updatedAt: "2024-01-01T10:00:00.000Z",
  },
  {
    id: "seed-res-2",
    title: "Tech Interview Handbook",
    description: "Free curated interview preparation materials for software engineers.",
    url: "https://www.techinterviewhandbook.org/",
    category: ResourceCategory.Recruitment,
    type: ResourceType.Website,
    tags: ["interviews", "coding", "behavioral"],
    createdAt: "2024-01-02T10:00:00.000Z",
    updatedAt: "2024-01-02T10:00:00.000Z",
  },
  {
    id: "seed-res-3",
    title: "System Design Primer",
    description: "Learn how to design large-scale systems.",
    url: "https://github.com/donnemartin/system-design-primer",
    category: ResourceCategory.SystemDesign,
    type: ResourceType.Doc,
    tags: ["system design", "scalability", "architecture"],
    notes: "Essential for senior roles.",
    createdAt: "2024-01-03T10:00:00.000Z",
    updatedAt: "2024-01-03T10:00:00.000Z",
  },
  {
    id: "seed-res-4",
    title: "Harvard's CS50",
    description: "Introduction to Computer Science from Harvard.",
    url: "https://cs50.harvard.edu/",
    category: ResourceCategory.LeetCode,
    type: ResourceType.Video,
    tags: ["fundamentals", "free"],
    createdAt: "2024-01-04T10:00:00.000Z",
    updatedAt: "2024-01-04T10:00:00.000Z",
  },
  {
    id: "seed-res-5",
    title: "LinkedIn Jobs",
    description: "Primary job board for tech positions.",
    url: "https://www.linkedin.com/jobs/",
    category: ResourceCategory.JobBoards,
    type: ResourceType.Website,
    tags: ["jobs", "networking"],
    createdAt: "2024-01-05T10:00:00.000Z",
    updatedAt: "2024-01-05T10:00:00.000Z",
  },
  {
    id: "seed-res-6",
    title: "Resume Template – Jake's Resume",
    description: "Clean LaTeX resume template widely used in tech.",
    url: "https://www.overleaf.com/latex/templates/jakes-resume/syzfjbzwjncs",
    category: ResourceCategory.Resume,
    type: ResourceType.Template,
    tags: ["resume", "latex", "template"],
    notes: "Best clean format for SWE roles.",
    createdAt: "2024-01-06T10:00:00.000Z",
    updatedAt: "2024-01-06T10:00:00.000Z",
  },
  {
    id: "seed-res-7",
    title: "Blind 75 LeetCode Questions",
    description: "The original curated list of 75 essential LeetCode problems.",
    url: "https://leetcode.com/discuss/general-discussion/460599/blind-75-leetcode-questions",
    category: ResourceCategory.LeetCode,
    type: ResourceType.Article,
    tags: ["leetcode", "must-do", "patterns"],
    createdAt: "2024-01-07T10:00:00.000Z",
    updatedAt: "2024-01-07T10:00:00.000Z",
  },
  {
    id: "seed-res-8",
    title: "Behavioral Interview Questions – STAR Method",
    description: "Guide to answering behavioral questions using the STAR framework.",
    url: "https://www.indeed.com/career-advice/interviewing/how-to-use-the-star-interview-response-technique",
    category: ResourceCategory.Behavioral,
    type: ResourceType.Article,
    tags: ["behavioral", "STAR", "interview prep"],
    createdAt: "2024-01-08T10:00:00.000Z",
    updatedAt: "2024-01-08T10:00:00.000Z",
  },
];
